// Temporary dummy users for admin users page
export const dummyUsers = [
    {
      id: "u1",
      name: "Jane Cooper",
      email: "jane.cooper@rahulkumar.com",
      role: "UI/UX Designer",
      phone: "0987654321",
      alternateMobile: "0123456789",
      address: "Madhapur, Hyderabad",
      department: "Design",
      designation: "Senior Designer",
    },
    {
      id: "u2",
      name: "Rohit Sharma",
      email: "rohit.sharma@rahulkumar.com",
      role: "Frontend Engineer",
      phone: "9876501234",
      alternateMobile: "0112233445",
      address: "Baner, Pune",
      department: "Engineering",
      designation: "Software Engineer",
    },
    {
      id: "u3",
      name: "Priya Nair",
      email: "priya.nair@rahulkumar.com",
      role: "HR Manager",
      phone: "9000001234",
      alternateMobile: "0223344556",
      address: "Koramangala, Bengaluru",
      department: "HR",
      designation: "Manager",
    },
    {
      id: "u4",
      name: "Arjun Verma",
      email: "arjun.verma@rahulkumar.com",
      role: "Backend Engineer",
      phone: "9812345678",
      alternateMobile: "0192837465",
      address: "Noida, NCR",
      department: "Engineering",
      designation: "Senior Engineer",
    },
    {
      id: "u5",
      name: "Simran Kaur",
      email: "simran.kaur@rahulkumar.com",
      role: "Product Manager",
      phone: "9123456780",
      alternateMobile: "0172635478",
      address: "Andheri, Mumbai",
      department: "Product",
      designation: "PM",
    },
  ];
  